### ISSUE TITLE
Release context-free-grammar-0.1.1

### ISSUE THREAD

**Issue by andreasabel** [nedervold/context-free-grammar#3]
@nedervold thanks for merging my PR.

Would you mind releasing this as e.g. 0.1.1 on hackage?

**Comment by nedervold** [comment]
Working on it in my (limited) free time.

**Comment by nedervold** [comment]
Published [v0.1.1](https://hackage.haskell.org/package/context-free-grammar-0.1.1) to Hackage.  Waiting overnight to see if the server can build the docs.

**Comment by nedervold** [comment]
Everything looks fine.
